version: '3.8'

services:
  departure-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    image: departure-monitor:latest
    container_name: departure-monitor
    restart: unless-stopped
    ports:
      - "8080:80"  # Map container port 80 to host port 8080
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # For volume mounting during development (comment out in production)
    # volumes:
    #   - ./dist:/usr/share/nginx/html:ro
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - departure-monitor-network

networks:
  departure-monitor-network:
    driver: bridge