name: Container Registry CleanUp

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  
jobs:
  delete-untagged-images:
    name: Clean Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: false
          delete-tags: sha256:*
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true


