name: Container Registry CleanUp

on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'Only dry-run'
        required: true
        type: boolean
  
jobs:
  delete-untagged-images:
    name: Clean Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: ${{ inputs.dryrun }}
          delete-tags: sha256:*
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true


